version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/instance
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

volumes:
  sqlite_data:
    name: paasaiy_sqlite_data 